import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./Providers"; // Импортируем обёртку
import { MainHeader } from "@/Components/main/MainHeader";
import Breadcrumbs from "@/Components/Breadcrumbs/Breadcrumbs";
import { Footer } from "@/Components/footer/footer";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
            <Providers>
        <MainHeader />
        <Breadcrumbs />
     
    
              {children}
              <Footer />
        </Providers>
      
        
      </body>
    </html>
  );
}
